### PR TITLE
Added LVM support into initramfs.

### PR DESCRIPTION
**Pull request by bolshevik**
Currently XBian has a custom kernel with LZ4 support in Btrfs. LZ4 support is not available in the mainline kernel and it means that the filesystem cannot be read outside the XBian. In case of filesystem failure, the only way to extract files from the filesystem is compiling a custom kernel or running copying on the Raspberry PI, which is very slow. Furthermore, the Btrfs is not yet marked as production ready.

Alternative option is using any other file system supported by the XBian kernel. LVM is a great addition to EXT4 for example and might be useful for people hosting the data on EXT4 rather than Btrfs.

This patch allows to embed LVM tools and kernel modules into initramfs and mount file systems located in LVM.

### CODE REVIEW

**Comment by bolshevik** [comment]
Here is an updated version. It works as you were suggesting. Please review.

**Comment by mk01** [comment]
@bolshevik 

just maybe one more thing to consider - you added support for lvm in general through dm, but what about the all different storage configurations? is not this dependent on the other modules in ./kernel/drivers/md like dm-raid, dm-mirror ...

or lvm itself is different subsystem dependent only on device mapper base support and handles the configurations differently?

**Comment by bolshevik** [comment]
There are two different subsystems provided by these drivers https://www.kernel.org/doc/menuconfig/drivers-md-Kconfig.html#MD . One should not mix RAID and LVM. Yes, there are software RAID drivers, but they are not needed for the LVM to function, on the other hand yes, the LVM might be distributed across several block devices using builtin device mapper or a software or a hardware RAID.

The aim of LVM is to create virtual block devices by combining lower level block devices. It does not offer any redundancy, but it offers a dynamical management of the logical volumes. The LV can be transparently moved across devices or copied to a new device without breaking addressing of the block device. It does not pay attention to file systems located on the LV and operates on a block level. The move can be done online. If there is a free block pool, LVM might use it for snapshotting. The existing blocks are frozen and new writes happen to the unallocated block pool. One might call LVM as JBOD, because there is no redundancy or striping, I am not sure about the algorithms used to allocate blocks across lower block devices and if a redundancy or stripping possible.

RAID drivers, on the other hand implement different RAID levels and they also use the dm-mod to create virtual block devices based on other block devices. RAID was not aimed by this PR.

There is also another interesting kernel module dm-crypt used to perform a block level encryption of the drive. I don't think it is relevant for embedded platforms due to performance. Therefore it is also not needed.

Finally, there are additional dm-modules, which might be used by LVM, per my understanding some of them are used for testing, and others are needed for live operations and can be loaded from a mounted rootfs. There is no need to have those modules in the pre-boot environment. I tried to make this as minimal as possible. Of course, all the dm-modules can be copied into the initramfs, but I don't think those will ever be used.

**Comment by CurlyMoo** [comment]
A question i ask to all skilled people :smile: Care to join XBian in whatever way?

**Comment by bolshevik** [comment]
Hi there again! After recent update Xbian fails to start on the RPi2, the reason is the file /etc/init/xbmc.conf . It references /dev/mxc_ipu device. I cannot find this commit in the xbian-package-xbmc-scripts repo. How would be the best to submit a patch?

This line fails:
```
chmod 660 /dev/mxc_ipu /dev/fb? ; chown root:video /dev/mxc_ipu /dev/fb?
```

**Comment by mkreisl** [comment]
The best way would be to make a PR, but unfortunately the current version of the package xbmc-package-xbmc-scripts is not on github

@mk01 
could you please look into

**Pull request merged**
